CREATE TABLE IF NOT EXISTS `agent_execution` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `execution_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `agent_id` VARCHAR(32) NOT NULL,
  `model_id` VARCHAR(64) NOT NULL DEFAULT '',
  `route_type` VARCHAR(24) NOT NULL DEFAULT 'react',
  `status` VARCHAR(24) NOT NULL DEFAULT 'RUNNING',
  `current_cycle` INT NOT NULL DEFAULT 0,
  `current_step` INT NOT NULL DEFAULT 0,
  `max_cycles` INT NOT NULL DEFAULT 5,
  `max_steps` INT NOT NULL DEFAULT 30,
  `state_json` MEDIUMTEXT NULL,
  `last_assistant_content` MEDIUMTEXT NULL,
  `error_message` TEXT NULL,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_execution_id` (`execution_id`),
  KEY `idx_agent_execution_session` (`session_id`,`started_at`),
  KEY `idx_agent_execution_agent` (`agent_id`,`started_at`),
  KEY `idx_agent_execution_status` (`status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
